name: Gogstash
on: [push, pull_request, workflow_dispatch]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: golangci/golangci-lint-action@v6
      with:
        args: --verbose --timeout=5m

  build:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CACHE_VERSION: 2024-02-08.1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test -v ./...
    - run: go build
